# Generated by Django 4.1 on 2022-08-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_language', models.CharField(max_length=20)),
                ('book_price', models.CharField(max_length=10)),
                ('book_page', models.CharField(max_length=10)),
                ('book_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('birth_place', models.CharField(max_length=20)),
                ('book_write', models.ManyToManyField(related_name='book', to='book.book')),
            ],
        ),
    ]
